language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install python-numpy python-scipy libzmq3-dev
install: 
  - LANG=C pip install pyzmq
  - LANG=C pip install dsltools
  - LANG=C pip install cython
  - LANG=C pip install parakeet
  - LANG=C pip install scikit-learn
  - LANG=C pip install traits 
  - LANG=C python setup.py develop --user
script: nosetests -v --logging-level=INFO --logging-clear-handlers --logging-format='%(filename)s:%(lineno)s [%(funcName)s] %(message)s'
